### ISSUE TITLE
adopters page: not all cards are equal height

### ISSUE THREAD

**Issue by dholbach** [fluxcd/website#208]
![Screenshot from 2021-05-05 18-34-42](https://user-images.githubusercontent.com/1346979/117176821-989a8b80-add0-11eb-9ffc-7be7e0a69941.png)

In this case, the last entry being the only one in its `card-deck`.

**Comment by juozasg** [comment]
Has this been fixed in another commit?

https://fluxcd.io/adopters/

**Comment by dholbach** [comment]
Apparently. Well done whoever it was! :fireworks:

**Comment by dholbach** [comment]
This is still an issue, from today:

![Screenshot from 2021-06-28 15-46-50](https://user-images.githubusercontent.com/1346979/123647139-1f477400-d828-11eb-881f-fdfa519499e4.png)
